# Generated by Django 3.2.23 on 2024-01-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='privacy',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
