# Generated by Django 3.2.23 on 2023-11-22 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('overdue', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[('WORK', 'Work'), ('PERSONAL', 'Personal'), ('HOME', 'Home'), ('HEALTH', 'Health'), ('FINANCE', 'Finance'), ('EDUCATION', 'Education'), ('SHOPPING', 'Shopping'), ('TRAVEL', 'Travel'), ('HOBBIES', 'Hobbies'), ('SOCIAL', 'Social')], max_length=100)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
