# Generated by Django 3.2.23 on 2023-11-22 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owners',
            field=models.ManyToManyField(related_name='owned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
