# Generated by Django 3.2.23 on 2023-12-08 10:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
